/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kalkulator;

import javax.swing.JFrame;

/**
 *
 * @author Siti Zulfa Oktaviani
 */
public class KalkulatorSuhu extends javax.swing.JFrame {

    /**
     * Creates new form KalkulatorSuhu
     */
    public KalkulatorSuhu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        suhuAkhir = new javax.swing.JLabel();
        suhu = new javax.swing.JTextField();
        satuanAwal = new javax.swing.JComboBox();
        satuanAkhir = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tombolKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kalkulator Konversi Suhu"); // NOI18N
        setBackground(new java.awt.Color(47, 57, 59));

        jPanel1.setBackground(new java.awt.Color(47, 57, 59));

        jLabel1.setBackground(new java.awt.Color(47, 57, 59));
        jLabel1.setForeground(new java.awt.Color(47, 57, 59));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.jpg"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setIconTextGap(0);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Konversi Suhu");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        suhuAkhir.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        suhuAkhir.setForeground(new java.awt.Color(255, 255, 255));
        suhuAkhir.setText("Hasil");

        suhu.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N

        satuanAwal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        satuanAwal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Celcius", "Reamur", "Fahrenheat", "Kelvin" }));

        satuanAkhir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        satuanAkhir.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Celcius", "Reamur", "Fahrenheat", "Kelvin" }));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Suhu");

        tombolKembali.setBackground(new java.awt.Color(255, 255, 0));
        tombolKembali.setText("KEMBALI");
        tombolKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(suhu, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(suhuAkhir))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(satuanAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(satuanAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(118, 118, 118))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tombolKembali)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(212, 212, 212))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(suhu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(satuanAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(satuanAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(suhuAkhir)))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tombolKembali)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // celcius      
        if (satuanAwal.getSelectedItem().toString().equalsIgnoreCase("Celcius")&&satuanAkhir.getSelectedItem().toString().equalsIgnoreCase("Kelvin"))
        {
            float celcius = Float.parseFloat(suhu.getText());
            float hasil = celcius + 273;
            suhuAkhir.setText(hasil+" °K");   
        }
        else if (satuanAwal.getSelectedItem().toString().equalsIgnoreCase("Celcius")&&satuanAkhir.getSelectedItem().toString().equalsIgnoreCase("Fahrenheat"))
        {
            float celcius = Float.parseFloat(suhu.getText());
            float hasil = ((9*celcius)/5)+32;
            suhuAkhir.setText(hasil+" °F");   
        }
        else if (satuanAwal.getSelectedItem().toString().equalsIgnoreCase("Celcius")&&satuanAkhir.getSelectedItem().toString().equalsIgnoreCase("Reamur"))
        {
            float celcius = Float.parseFloat(suhu.getText());
            float hasil = (4*celcius)/5;
            suhuAkhir.setText(hasil+" °R");   
        }
        // celcius
        
        // reamur
        else if (satuanAwal.getSelectedItem().toString().equalsIgnoreCase("Reamur")&&satuanAkhir.getSelectedItem().toString().equalsIgnoreCase("Celcius"))
        {
            float reamur = Float.parseFloat(suhu.getText());
            float hasil = (5*reamur)/4;
            suhuAkhir.setText(hasil+" °C");   
        }
        else if (satuanAwal.getSelectedItem().toString().equalsIgnoreCase("Reamur")&&satuanAkhir.getSelectedItem().toString().equalsIgnoreCase("kelvin"))
        {
            float reamur = Float.parseFloat(suhu.getText());
            float hasil = ((5*reamur)/4)+273;
            suhuAkhir.setText(hasil+" °K");   
        }
        else if (satuanAwal.getSelectedItem().toString().equalsIgnoreCase("Reamur")&&satuanAkhir.getSelectedItem().toString().equalsIgnoreCase("Fahrenheat"))
        {
            float reamur = Float.parseFloat(suhu.getText());
            float hasil = ((9*reamur)/4)+32;
            suhuAkhir.setText(hasil+" °F");   
        }
        // reamur
        
        // fahrenheat
        else if (satuanAwal.getSelectedItem().toString().equalsIgnoreCase("Fahrenheat")&&satuanAkhir.getSelectedItem().toString().equalsIgnoreCase("Celcius"))
        {
            float fahrenheat = Float.parseFloat(suhu.getText());
            float hasil = (float) (0.5*(fahrenheat-32));
            suhuAkhir.setText(hasil+" °C");   
        }
        else if (satuanAwal.getSelectedItem().toString().equalsIgnoreCase("Fahrenheat")&&satuanAkhir.getSelectedItem().toString().equalsIgnoreCase("Reamur"))
        {
            float fahrenheat = Float.parseFloat(suhu.getText());
            float hasil = (float) (0.4*(fahrenheat-32));
            suhuAkhir.setText(hasil+" °R");   
        }
        else if (satuanAwal.getSelectedItem().toString().equalsIgnoreCase("Fahrenheat")&&satuanAkhir.getSelectedItem().toString().equalsIgnoreCase("Kelvin"))
        {
            float fahrenheat = Float.parseFloat(suhu.getText());
            float hasil = (float) (0.5*(fahrenheat-32))+273;
            suhuAkhir.setText(hasil+" °K");   
        }
        // fahrenheat  
        
        // kelvin
        else if (satuanAwal.getSelectedItem().toString().equalsIgnoreCase("Kelvin")&&satuanAkhir.getSelectedItem().toString().equalsIgnoreCase("Celcius"))
        {
            float kelvin = Float.parseFloat(suhu.getText());
            float hasil = kelvin - 273;
            suhuAkhir.setText(hasil+" °C");   
        }
        else if (satuanAwal.getSelectedItem().toString().equalsIgnoreCase("Kelvin")&&satuanAkhir.getSelectedItem().toString().equalsIgnoreCase("Reamur"))
        {
            float kelvin = Float.parseFloat(suhu.getText());
            float hasil = (float) (0.8*(kelvin-273));
            suhuAkhir.setText(hasil+" °R");   
        }
        else if (satuanAwal.getSelectedItem().toString().equalsIgnoreCase("Kelvin")&&satuanAkhir.getSelectedItem().toString().equalsIgnoreCase("Fahrenheat"))
        {
            float kelvin = Float.parseFloat(suhu.getText());
            float hasil = (float) (1.8*(kelvin-273))+32;
            suhuAkhir.setText(hasil+" °R");   
        }
        // kelvin
        else{
            suhuAkhir.setText("Error");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tombolKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolKembaliActionPerformed
        // TODO add your handling code here:
        beranda home = new beranda();
        home.setVisible(true);
        home.pack();
        home.setLocationRelativeTo(null);
        home.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_tombolKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KalkulatorSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KalkulatorSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KalkulatorSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KalkulatorSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KalkulatorSuhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox satuanAkhir;
    private javax.swing.JComboBox satuanAwal;
    private javax.swing.JTextField suhu;
    private javax.swing.JLabel suhuAkhir;
    private javax.swing.JButton tombolKembali;
    // End of variables declaration//GEN-END:variables
}
